Add ToDoList
tatianashulzhik/practice pull request #1
Opened 2023-12-20 14:39 UTC by tatianashulzhik

2023-12-21 10:37 UTC, baklanovairina requested changes

2023-12-21 10:37 UTC, baklanovairina commented on app.js
> +app.use("/", apiRoutes);
это должно идти до объявления loadApp

2023-12-21 10:37 UTC, baklanovairina commented on app.js
> +app.post("/", (req, res) => {
это здесь зачем?

2023-12-21 10:37 UTC, baklanovairina commented on app.js
> +app.get("/", (req, res) => {
это тоже явно лишнее

2023-12-21 10:37 UTC, baklanovairina commented on src/controllers/tasc-controllers.js
> +module.exports = {
отступ в 1 строку перед module.exports

и где остальной функционал? Это редактирование текста задачи, редактирования чекбокса/статуса задачи, удаление одной задачи и удаление всех задач сразу

2023-12-21 10:37 UTC, baklanovairina commented on src/middlwares/task-validation.js
> +const validationText = [check("text").isString().trim().notEmpty()];
переносы пожалуйста правильно делай и табы

2023-12-21 10:37 UTC, baklanovairina commented on src/routes/task.js
> +const router = express.Router();
это желательно создавать уже после импортов здесь

2023-12-21 10:37 UTC, baklanovairina commented on src/services/tasc-services.js
> +  return savedTask;
отступы 1 одну строку перед return делаем

2023-12-21 11:55 UTC, tatianashulzhik commented on app.js
> +app.post("/", (req, res) => {
24. вызываем метод express.json() в качестве промежуточного программного обеспечения для распознавания входящего объекта запроса как объект JSON 
25. импортируем и запускаем роуты в приложении
27. применяла знания на практике, сейчас уберу

2023-12-22 06:20 UTC, baklanovairina requested changes

2023-12-22 06:20 UTC, baklanovairina commented on app.js
> +// const Task = require("./scr/models/task");
никаких комментов здесь не должно быть

2023-12-22 06:20 UTC, baklanovairina commented on src/controllers/tasc-controllers.js
>      const task = await createTask(text);
от переменных/деструктруризации делай отступ в 1 пустую строку пожалуйста
вообще логические блоки нужно отделять между собой 1ой пустой строкой

2023-12-22 06:20 UTC, baklanovairina commented on src/controllers/tasc-controllers.js
> +const updateisCheck = async (req, res) => {
updateCheck, а не updateis - такого слова нет

2023-12-22 06:20 UTC, baklanovairina commented on src/controllers/tasc-controllers.js
> +    const { isCheck } = req.body;
тоже отступ, везде проверь и исправь, чтобы я не повторялась

2023-12-22 06:20 UTC, baklanovairina commented on src/controllers/tasc-controllers.js
> +    const { isCheck } = req.body;
кстати, а где айди? Как ты без айди определяешь в каком элементе нужно изменить чекбокс?

2023-12-22 06:20 UTC, baklanovairina commented on src/controllers/tasc-controllers.js
> +const updateManyTask = async (req, res) => {
почему много тасков? Нельзя изменить за раз сразу несколько задач, изменяется только 1

2023-12-22 06:20 UTC, baklanovairina commented on src/controllers/tasc-controllers.js
> +    const { text } = req.body;
опять же где айди?

2023-12-22 06:20 UTC, baklanovairina commented on src/controllers/tasc-controllers.js
> +    const { text } = req.body;
зачем тебе для удаления всех тасков текст?

2023-12-22 06:20 UTC, baklanovairina commented on src/controllers/tasc-controllers.js
> +    const { text } = req.body;
и снова зачем текст, когда нужен айди таска, который ты хочешь удалить

2023-12-22 06:20 UTC, baklanovairina commented on src/middlwares/task-validation.js
> +    .notEmpty()];
табы 2 пробела и после check тоже нужны табы
```
    check("text")
      .isString()
      .trim()
      .notEmpty()];
```

2023-12-22 06:20 UTC, baklanovairina commented on src/middlwares/task-validation.js
нет валидации для чекбокса

2023-12-22 06:20 UTC, baklanovairina commented on src/routes/task.js
> +router.put("/tasks", updateManyTask);
это не put, а patch
еще раз почитай чем они отличаются и поймешь почему лучше patch
кроме того, нет динамического параметра id
"/tasks/:id"

2023-12-22 06:20 UTC, baklanovairina commented on src/routes/task.js
> +router.delete("/tasks/:id", deleteOneTasks);
очень странно, а здесь пишешь что по айди удаление, хотя в контроллерах ты пытаешься уже достать текст вместо айди

скажи, пожалуйста, вы работу своего приложения тестировала в Постмане, просто ощущение, что нет, так как это работать не будет

2023-12-22 06:20 UTC, baklanovairina commented on src/routes/task.js
> +router.put("/isCheck/:id", updateisCheck);
isCheck- некорректное название для роута, в материалах есть полезная ссылка на доп инфц по rest api, почитай ее пожалуйста
там описаны лучшие практики

и тоже странно конечно, вроде пишешь айди здесь, а в контроллерах достаешь снова текст

2023-12-22 06:20 UTC, baklanovairina commented on src/services/tasc-services.js
> +  let data = await Task.updateMany({ text });
почем let везде ставишь? Если данные не изменяются, то они всегда const

2023-12-22 06:20 UTC, baklanovairina commented on src/services/tasc-services.js
> +  let data = await Task.updateMany({ text });
и не data - слишком абстрактное название, не понятно, что возвращается,
называй переменную согласно тому, что в нее возвращается и хранится

2023-12-25 08:31 UTC, closed without merging